### ISSUE TITLE
Adjusting for other languages

### ISSUE THREAD

**Issue by AnnCod** [BakerBunker/SALT#1]
Hi,

Do you think that this solution can be adapted easily to work on different languages than English?

**Comment by AnnCod** [comment]
Thanks for the reply. Is this demo working correctly? I have some errors while trying to run it on colab.

**Comment by BakerBunker** [comment]
Sorry, I accidentally misspelled a variable name, fixed by https://github.com/BakerBunker/SALT/commit/8060405da51996c0b8b47a5b8c2babad0838b14a

**Comment by AnnCod** [comment]
but there's still an error "RuntimeError: The size of tensor a (23866) must match the size of tensor b (214) at non-singleton dimension 2"

**Comment by BakerBunker** [comment]
I can't reproduce this error, would you consider share your colab notebook with these output?
